spring:
  application:
    name: marketing-timeline-api-server
  profiles:
    group:
      local: db-local
      prod: db-prod
      aws: db-aws
  config:
    import: "classpath:application-db.yaml"

server:
  port: 8086